export const SET_SINGER = 'SET_SINGER';

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY';

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY';

export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST';